# starship.toml

[username]
show_always = true
style_user = "bold white"
format = "[$user]($style)"

[hostname]
ssh_only = false
format = "[$hostname]($style) "
style = "bold white"

[directory]
truncation_length = 3
format = "[$path]($style) "
style = "cyan"

[git_branch]
format = "[$branch]($style) "
style = "bold purple"

[git_status]
format = "([$status]$style)"
style = "bold yellow"
disabled = false

[time]
format = "[$time]($style) "
style = "bold green"
disabled = false
time_format = "%Y-%m-%d %H:%M:%S"

[gcloud]
format = "[$symbol($project)]($style) "
style = "bold blue"
disabled = false

[azure]
format = "[$symbol($subscription)]($style) "
style = "bold blue"
disabled = false

[aws]
format = "[$symbol($profile)]($style) "
style = "bold blue"
disabled = false

[digitalocean]
format = "[$symbol($profile)]($style) "
style = "bold blue"
disabled = false
